export default {
  login: 'freeCodeCamp',
  id: 9892522,
  node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
  avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/freeCodeCamp',
  html_url: 'https://github.com/freeCodeCamp',
  followers_url: 'https://api.github.com/users/freeCodeCamp/followers',
  following_url:
    'https://api.github.com/users/freeCodeCamp/following{/other_user}',
  gists_url: 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/freeCodeCamp/subscriptions',
  organizations_url: 'https://api.github.com/users/freeCodeCamp/orgs',
  repos_url: 'https://api.github.com/users/freeCodeCamp/repos',
  events_url: 'https://api.github.com/users/freeCodeCamp/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/freeCodeCamp/received_events',
  type: 'Organization',
  site_admin: false,
  name: 'freeCodeCamp.org',
  company: null,
  blog: 'https://freecodecamp.org',
  location: 'Just here on Earth... for now',
  email: null,
  hireable: null,
  bio: 'Learn to code for free with millions of other people around the world',
  twitter_username: 'freeCodeCamp',
  public_repos: 208,
  public_gists: 5,
  followers: 8780,
  following: 0,
  created_at: '2014-11-22T00:12:57Z',
  updated_at: '2023-02-04T12:18:53Z',
}
